### ISSUE TITLE
AoT build failed after 2.0.0

### ISSUE THREAD

**Issue by vincent-cm** [PillowPillow/ng2-webstorage#76]
Error: Metadata version mismatch for module ---/node_modules/ng2-webstorage/dist/interfaces/config.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (---/node_modules/@angular/compiler/@angular/compiler.es5.js:25586:7)
    at StaticSymbolResolver._createSymbolsOf (---/node_modules/@angular/compiler/@angular/compiler.es5.js:25374:10)
    at StaticSymbolResolver.getSymbolsOf (---/node_modules/@angular/compiler/@angular/compiler.es5.js:25355:12)
    at ---/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (---/node_modules/@angular/compiler/@angular/compiler.es5.js:24210:55)
    at AotCompiler.analyzeModulesAsync (---/node_modules/@angular/compiler/@angular/compiler.es5.js:23766:7)
    at CodeGenerator.codegen (---/packages/compiler-cli/src/codegen.ts:41:10)
    at ---/node_modules/src/main.ts:19:84
    at Object.main (/Users/matrix/Desktop/iDigiSign/tools/@angular/tsc-wrapped/src/main.ts:136:12)
    at Object.runInternal (---/node_modules/src/main.ts:24:10)
    at ---/node_modules/src/plugin.ts:64:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by PillowPillow** [comment]
Hi, which version of angular & angular cli are you using? The v2.0.0 requires angular 5
