### ISSUE TITLE
angular universal support

### ISSUE THREAD

**Issue by PillowPillow** [PillowPillow/ng2-webstorage#79]

**Comment by AnthonyNahas** [comment]
that would be grate! 

using firebase deploy.. I am getting this error

```sh 
i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

/.../functions/node_modules/ngx-webstorage/dist/services/sessionStorage.js:11
import { Injectable } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)

```

here is a link on how I fixed similar issues...

https://github.com/SebastianM/angular-google-maps/issues/1052

**Comment by marticrespi** [comment]
Is planned the universal support? @PillowPillow

**Comment by PillowPillow** [comment]
Yes it planned, i just don't have time at this moment to add this feature. A PR would be really appreciated!

**Comment by AnthonyNahas** [comment]
@PillowPillow @marticrespi I've just pulled a new request solving this problem
